### ISSUE TITLE
Please include documentation about our basic CRUD data model API

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/Zendro-dev.github.io#1]
So far we have no complete and comprehensive documentation about the default CRUD API that Science-DB uses for it's data models. However there is [document already describing a major part of it](https://docs.google.com/document/d/1icuxeKuG6olwPbAxNrxuciWjmQ91YpP7RoQ8p-y6TV0/edit?usp=sharing). 

Please add a chapter that explains very briefly which basic CRUD functions are made available and then shows an example. Use the [above document](https://docs.google.com/document/d/1icuxeKuG6olwPbAxNrxuciWjmQ91YpP7RoQ8p-y6TV0/edit?usp=sharing) as a starting point. In difference to the examples given in the document please use the GraphQL schema definitions of the respective mutations and queries.

Please also add documentation about queries and mutations (CRUD interfaces) concerning all kinds of both types, i.e. has-one and has-many relationships.

## Expected work time: 2h

**Comment by asishallab** [comment]
### Please include in the above documentation a detailed description of the arguments each query and mutations receives.

**Comment by vsuaste** [comment]
Done. Commits [#f67162](https://github.com/ScienceDb/ScienceDb.github.io/commit/f67162dd6976fe4b68a7b45b411eb7ec805519c8) [#5bc56e](https://github.com/ScienceDb/ScienceDb.github.io/commit/5bc56eaa1548078cc14ae29b509eba1e10e3e741)
