### ISSUE TITLE
Add recommended model name format: Only lower-case letters and "_" (snake_case)

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/Zendro-dev.github.io#5]
Let the user clearly and strongly know that we only recommend defining models with lower-case names and to separate words the usage of "_" (snake_case). Also model names should be singular.

Particularly mention the term "snake_case".

### Expected work time: 1h

**Comment by AliciaMstt** [comment]
These recommendations are not necessary any more, maybe only for standard use, but the code should work in any case.
